### ISSUE TITLE
Consider making a SMPTE library

### ISSUE THREAD

**Issue by AndColla** [MrExplode/Timecode#2]
Hi, this is kinda unrelated, but I did't find a another way to contact you.
There is a project witch works with Pioneer Link protocol and it wold be nice to generate a SMPTE signal from it. I saw your project and it quite fit, but there are a few problems. Maybe I'm wrong, but as far as I digged thru your code the timecode implementation is snarled together with some ArtNet and OSC code, there is no clear separation of concerns. Also, there does not seem to be any way to change the speed at which timecode runs (not the frame rate, but saying “pretend time is passing slower or faster”) which is necessary to support DJ pitch adjustments.
Here's a link to the project: https://gitter.im/brunchboy/beat-link-trigger
Moreover you did't specify a licence for this project, so I don't know what i can do with your code.

**Comment by AndColla** [comment]
Another solution could be to use OSC to remote control your software. You’ll still need to add the pitch control feature and reverse direction feature, but that would be a more stable solution than integrating it in Beat Link Trigger.

**Comment by MrExplode** [comment]
Hello there!
Currently this app is only for generating signals, no converting can be done. The smtpe is "generated" by playing back a simple pre-generated file. The only open-source library available for actually generating smtpe LTC signals is [libltc](https://github.com/x42/libltc) and it's written in C.
I'm only comfortable with Java.
If you need a complete solution for production, TimelordMTC (not free, but demo available) might be able to do it.
If you need an api, or something you can develop on your own, you can try with libltc, or implementing your own from the [smpte specification](https://en.wikipedia.org/wiki/Linear_timecode)

**Comment by MrExplode** [comment]
Hey @AndColla !
I changed my mind, and wrote a library for ltc. Just finished coding it, and didn't run it once, and haven't tested it yet, but you might want to take a look at it.
The library called ltc4j and available [here](https://github.com/MrExplode/ltc4j). I will publish it into the maven central later.
At this moment it's just started, I will write proper documentation, examples etc etc
